stages:
  test:
    cmd: Rscript test.R
    deps:
      - test.R
  download_ons:
    cmd: Rscript .pipelines/run_ons_update.R
    always_changed: true
    deps:
      - .pipelines/run_ons_update.R
      - R/
