name: pipeline
'on':
  workflow_dispatch: {}
jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-renv@v2
      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install dvc
        run: pip install dvc

      - name: Generate data
        run: dvc repro
