name: pipeline
'on':
  workflow_dispatch: {}
jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check-out repo
        uses: actions/checkout@v3

      - name: 'Install R v4.2.3'
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.2.3'
          use-public-rspm: true

      - name: Setup {renv}
        uses: r-lib/actions/setup-renv@v2

      - name: Setup {pandoc}
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install dvc
        run: pip install dvc

      - name: Generate data
        run: dvc repro
