name: pipeline
'on':
  workflow_dispatch: {}
jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Check-out repo
        uses: actions/checkout@v4

      - name: 'Install R'
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: renv
          use-public-rspm: true
      
      - name: Install system dependencies
        run: sudo apt-get install --yes libgdal-dev libgeos-dev libproj-dev libudunits2-dev

      - name: Setup {renv}
        uses: r-lib/actions/setup-renv@v2
        # with:
        #   profile: pipeline

      - name: Setup {pandoc}
        uses: r-lib/actions/setup-pandoc@v2

      - name: Install dvc
        run: pip install dvc

      - name: Generate data
        run: dvc repro

      - name: Set current date
        run: echo "NOW=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update ONS datasets $NOW
          # file_pattern: data-raw data
